export const FATCH_ORDER_START = 'FATCH_ORDERS_START';
export const FATCH_ORDERS_SUCCESS = 'FATCH_ORDERS_SUCCESS';
export const FATCH_ORDERS_FAILED = 'FATCH_ORDERS_FAILED';
export const DEL_ORDER = 'DEL_ORDER';