export const SUBMIT_ORDER_START = 'SUBMIT_ORDER_START';
export const SUBMIT_ORDER_SUCCESS = 'SUBMIT_ORDER';
export const SUBMIT_ORDER_FAILED = 'SUBMIT_ORDER_FAILED';
export const REDIRECT_AFTER_SUBMIT = 'REDIRECT_AFTER_SUBMIT';
